version: 2

conda:
  environment: environment.yml

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install -e . --no-deps
      - pip install myst-parser

sphinx:
  configuration: conf.py
