name: forecasting
channels:
  - conda-forge
dependencies:
  - firecrown >=1.14.0,<1.15.0
  - flake8
  - scipy < 1.14.0
  - healpy
  - jinja2
  - numdifftools
  - numpydoc
  - qp-prob
  - tjpcov >= 0.5.1
  - pyccl >= 3.3.1
  - derivkit
