name: forecasting
channels:
  - conda-forge
dependencies:
  - numpy >= 2.0
  - firecrown >= 1.14.0
  - flake8
  - scipy > 1.12
  - healpy
  - jinja2
  - numdifftools
  - numpydoc
  - qp-prob
  - tjpcov
  - pyccl >= 3.3.1
  - sphinx
  - myst-parser
  - pyyaml
