
name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: augur
        
    - name: Checkout firecrown
      uses: actions/checkout@v2
      with:
        repository: LSSTDESC/firecrown
        path: firecrown

    - name: Install dependencies
      run: |
        conda activate base
        conda install -q -c conda-forge --only-deps firecrown
        cd firecrown
        pip install --no-deps -e .
        conda install -q flake8
        conda install -q pytest

    - name: Environment test
      shell: bash -l {0}
      run: |
        conda info
        conda activate base
        which python
        python -c "import numpy; print (numpy.__path__)"
        python -c "import pyccl; print (pyccl.__path__)"
        python -c "import firecrown.ccl; print (firecrown.__path__)"
        
    - name: Lint with flake8
      shell: bash -l {0}
      run: /usr/share/miniconda/bin/flake8 augur --max-line-length=100 --count --show-source --statistics

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        conda activate base
        cd augur
        /usr/share/miniconda/bin/pytest
