
name: flake8 pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: augur
        
    - name: Checkout firecrown
      uses: actions/checkout@v2
      with:
        repository: LSSTDESC/firecrown
        ref: refs/tags/v1.6.0
        path: firecrown

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda activate base
        conda install -q -c conda-forge --only-deps firecrown
        cd firecrown
        pip install numdifftools
        pip install --no-deps -e .
        conda install -q flake8
        conda install -q pytest
        conda install -q matplotlib
        conda install -q numdifftools -c conda-forge
        cd ..
        git clone https://github.com/LSSTDESC/TJPCov.git
        cd TJPCov
        pip install --no-deps -e .
    - name: Environment test
      shell: bash -l {0}
      run: |
        conda info
        conda activate base
        which python
        
    - name: flake8
      shell: bash -l {0}
      run: /usr/share/miniconda/bin/flake8 augur --max-line-length=100 --count --show-source --statistics

    - name: pytest
      shell: bash -l {0}
      run: |
        conda activate base
        cd augur
        /usr/share/miniconda/bin/pytest
