
name: flake8 pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: augur
        
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda env update -f augur/environment.yml
        conda activate forecasting
        cd augur
        python -m pip install --no-deps --editable .

    - name: flake8
      shell: bash -l {0}
      run: flake8 --max-line-length=100 --count --show-source --statistics

    - name: pytest
      shell: bash -l {0}
      run: |
        conda activate forecasting
        cd augur
        /usr/share/miniconda/bin/pytest
