
name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout firecrown
      uses: actions/checkout@v2
      with:
        repository: LSSTDESC/firecrown
        path: firecrown

    - name: Install dependencies
      run: |
        conda install -c conda-forge --only-deps firecrown
        pip install --no-deps firecrown/
        
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are flake8 fails
        flake8 . --count --show-source --statistics

    - name: Test with pytest
      run: |
        conda install pytest
        pytest
